# Generated by Django 4.2.11 on 2024-03-28 11:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Розділ',
                'verbose_name_plural': 'Розділи',
            },
        ),
        migrations.CreateModel(
            name='Subsection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_subsection', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subsections', to='main.section')),
            ],
            options={
                'verbose_name': 'Підрозділ',
                'verbose_name_plural': 'Підрозділи',
            },
        ),
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('tag', models.CharField(choices=[('p', 'Paragraph'), ('li', 'List Item')], max_length=2)),
                ('subsection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.subsection')),
            ],
            options={
                'verbose_name': 'Вміст',
                'verbose_name_plural': 'Вміст',
            },
        ),
    ]
