# Generated by Django 4.2.11 on 2024-03-28 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subsection',
            name='slogan',
            field=models.TextField(blank=True, null=True),
        ),
    ]
