# Generated by Django 4.2.11 on 2024-03-28 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_subsection_slogan'),
    ]

    operations = [
        migrations.AddField(
            model_name='subsection',
            name='alt_text',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='subsection',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media/portfolio_images/'),
        ),
    ]
