# Generated by Django 4.2.11 on 2024-03-28 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_subsection_alt_text_subsection_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='subsection',
            name='subtitle',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='subsection',
            name='slogan',
            field=models.TextField(blank=True, max_length=355, null=True),
        ),
    ]
